version: "3.8"

services:
  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: 
      - .env
    command: npm start
    ports:
      - 8001:8001
    networks:
      - api
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - '27017'
    networks:
      - api

networks:
  api:
    driver: bridge

volumes:
  mongodata:


